version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "cd next-app && yarn && yarn run dev"
    ports:
      - "8080:8080"
